/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/TicketInfo.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('element-plus/es')['ElInput']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelfInfo: typeof import('./src/components/SelfInfo.vue')['default']
    SystemInfo: typeof import('./src/components/SystemInfo.vue')['default']
    TicketInfo: typeof import('./src/components/TicketInfo.vue')['default']
    UserInfo: typeof import('./src/components/UserInfo.vue')['default']
    WeatherInfo: typeof import('./src/components/WeatherInfo.vue')['default']
  }
}
